apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: web
  namespace: ingress-demo
spec:
  ports:
    - name: web-traffic
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: web
  sessionAffinity: None
  type: LoadBalancer